_core:
  default_config_hash: g1xKHKD8msGv9RR5tnTxVhqTCkof96Cd4KF4mOLEntI
report-only:
  enable: true
  directives:
    default-src:
      base: self
    connect-src:
      sources:
        - 'https://www.google-analytics.com'
        - 'https://region1.google-analytics.com'
      base: self
    font-src:
      sources:
        - 'https://themes.googleusercontent.com'
        - 'https://fonts.gstatic.com'
        - 'https://use.fontawesome.com'
        - 'https://cdn.jsdelivr.net'
        - 'data:'
      base: self
    frame-src:
      sources:
        - 'https://www.youtube.com'
      base: self
    img-src:
      sources:
        - 'https://translate.google.com'
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
        - 'https://cdn.jsdelivr.net'
        - 'https://i.ytimg.com'
        - 'https://www.gstatic.com'
        - 'https://maps.gstatic.com'
        - 'https://maps.googleapis.com'
        - 'data:'
      base: self
    manifest-src:
      base: self
    script-src:
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
      base: self
    script-src-attr:
      base: self
    script-src-elem:
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
      base: self
    style-src:
      base: self
    style-src-attr:
      flags:
        - unsafe-inline
      base: self
    style-src-elem:
      base: self
    block-all-mixed-content: true
  reporting:
    plugin: sitelog
enforce:
  enable: false
  directives:
    default-src:
      base: self
    font-src:
      sources:
        - 'https://themes.googleusercontent.com'
        - 'https://fonts.gstatic.com'
        - 'https://use.fontawesome.com'
        - 'https://cdn.jsdelivr.net'
        - 'data:'
      base: self
    frame-src:
      sources:
        - 'https://www.youtube.com'
      base: self
    img-src:
      sources:
        - 'https://cdn.jsdelivr.net'
        - 'https://i.ytimg.com'
        - 'https://maps.gstatic.com'
        - 'https://maps.googleapis.com'
        - 'data:'
      base: self
    script-src:
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
      base: self
    script-src-elem:
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
      base: self
    style-src:
      base: self
    style-src-attr:
      flags:
        - unsafe-inline
      base: self
    style-src-elem:
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
      base: self
    block-all-mixed-content: true
  reporting:
    plugin: sitelog
