audit_button_text: 'Audit this published content'
audit_button_hover_text: 'Click this link to indicate you have checked this content for accuracy and relevance'
audit_confirmation_text: 'Click this button to indicate that you have audited this published content and are happy that it is still accurate and relevant.'
audit_content_types:
  page: page
  consultation: 0
  news: 0
  publication_page: 0
  staff_member: 0
  vacancy: 0
_core:
  default_config_hash: 3SEIckwYL56FAPOaQjHj9GcV2CUC9lkT-AxU07onAWE
